version: "2"

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./proxy/conf.d:/etc/nginx/conf.d"
      - "./proxy/vhost.d:/etc/nginx/vhost.d"
      - "./proxy/html:/usr/share/nginx/html"
      - "./proxy/certs:/etc/nginx/certs:ro"
      - "/tmp:/tmp"
    networks:
      - orbit
    # To have a default page when a service is down:
    # environment: 
      # - DEFAULT_HOST=https://status.defaultWebsite.com

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    networks:
      - orbit
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      # For staging server add following line:
      # - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
    networks:
      - orbit

networks:
  orbit:
    driver: bridge
