version: "2"

services:

  angular-satellite:
    restart: always
    image: angular-satellite
    build: ./angular_satellite_repo
    container_name: angular_satellite
    networks:
      - default
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=angular_satellite.com, www.angular_satellite.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=angular_satellite.com, www.angular_satellite.com
      - LETSENCRYPT_EMAIL=contact@angular_satellite.com
 
networks:
  default:
    external:
      name: spatioport_orbit
